version: '3.8'

services:
  # Web server with PHP
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs306_web
    ports:
      - "8080:80"
    volumes:
      - ./Phase_3/userandAdmin:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - mongodb
    networks:
      - cs306_network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: cs306_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cs306_project
      MYSQL_USER: cs306_user
      MYSQL_PASSWORD: cs306_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SQLDUMP.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cs306_network

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: cs306_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cs306_tickets
    volumes:
      - mongodb_data:/data/db
    networks:
      - cs306_network

  # phpMyAdmin for MySQL management
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cs306_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - cs306_network

  # MongoDB management interface
  mongo-express:
    image: mongo-express:latest
    container_name: cs306_mongo_express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8082:8081"
    depends_on:
      - mongodb
    networks:
      - cs306_network

volumes:
  mysql_data:
  mongodb_data:

networks:
  cs306_network:
    driver: bridge